site_name: Juan Pablo MkDocs Template
nav:
  - Home: index.md
  - About: about.md
  - How to Make a Ham and Cheese Sandwich: sandwich.md

theme:
  name: material
  palette:
    primary: black
    accent: indigo
  logo: images/wizeline_isotype.png
